### ISSUE TITLE
mix of absolute and relative paths for output directory

### ISSUE THREAD

**Issue by thymen** [ddos-clearing-house/ddos_dissector#14]
The method `check_requirements` checks whether the absolute path `/output` exists:

https://github.com/ddos-clearing-house/ddos_dissector/blob/b4385f0785af019441314c08768f2371bc4133f1/src/ddos_dissector_cli.py#L27

However, the directory `output` is created relative to the working directory if this condition is not met:

https://github.com/ddos-clearing-house/ddos_dissector/blob/b4385f0785af019441314c08768f2371bc4133f1/src/ddos_dissector_cli.py#L28

This bug makes it impossible to fulfill the `check_requirements` method (unless you run it from `/`). Using the same path in both lines would be a quick solution.

**Comment by jjsantanna** [comment]
Thanks @thymen! This was a lack of attention. Now it is fixed!
