### ISSUE TITLE
v3.01 uploads weird src_ips

### ISSUE THREAD

**Issue by poorting** [ddos-clearing-house/ddos_dissector#32]
version 3.01 seems to upload src_ips in this form:

  "src_ips": {
    "107.87.219.23": "107.87.219.23",
    "121.237.58.117": "121.237.58.117",
    "121.237.74.179": "121.237.74.179",
    "111.227.142.123": "111.227.142.123",
    "115.87.237.47": "115.87.237.47",
    "109.229.134.219": "109.229.134.219",
(...)

which ddosdb does not understand. 
Is there a reason for including src_ips in this way when the same information is also available in either amplifiers or attackers fields as a list?:

  "amplifiers": [
    "107.87.219.23",
    "121.237.58.117",
    "121.237.74.179",
    "111.227.142.123",
(...)

If there is no immediate reason for including src_ips, I would suggest to simply leave it out :-)

(by the way: this is also the reason that with default settings elasticsearch produces an error of 'Limit of total fields [1000] in index [ddosdb] has been exceeded', it treats every IP address key as a new field).

**Comment by poorting** [comment]
Original form of src_ips was something like this:
src_ips [
{
"ip": "107.87.219.23",
}
,
{
"ip": "121.237.58.117",
}
]
which ddosdb would then enrich with AS numbers and CCs:

src_ips [
{
"ip": "107.87.219.23",
"AS": "1234",
"CC": "NL".
}
(etc).

But if we need something like that then ddosdb can create that based on IPs in amplifiers/attackers :-)

**Comment by joaoceron** [comment]
src_ips field was removed. We are keeping a list of IPs using the field "amplifiers" or "attackers".
