### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ArriW** [ddos-clearing-house/ddos_dissector#33]
I am unsure how to fix this error.

```
  ./ddos_dissector.py -f pcap_samples/sample1.pcap --summary,
 
 Loading network file: `pcap_samples/sample1.pcap' ▁CRITICAL - Tshark software not found
 Exception in thread process:
 Traceback (most recent call last):
 File ...
 ...

TypeError: expected str, bytes or os.PathLike object, not NoneType
 Loading network file: `pcap_samples/sample1.pcap' ▁ 
```

**Comment by nhomble** [comment]
The program is analyzing pcap files so the assumption is that tshark is downloaded and on your ```PATH```. While I had wireshark locally, it turns out I had to manually append my path (windows). 

https://github.com/ddos-clearing-house/ddos_dissector/pull/34

**Comment by joaoceron** [comment]
Thanks @nhomble , I'll address this in the next release.

**Comment by joaoceron** [comment]
Done
