### ISSUE TITLE
ip_proto as a string

### ISSUE THREAD

**Issue by madibon** [ddos-clearing-house/ddos_dissector#35]
Could we also have the ip_proto as a string in the json fingerprint file?  Instead of or in addition to

 `
"ip_proto":[
      17
   ],
`
I'd need 

 `
"ip_proto_s":[
      "UDP"
   ],
`

Thank you!

**Comment by joaoceron** [comment]
Thank you @madibon , I will address this in the next release (next week 👍 

Sorry for the delay. I appreciate your comment.

**Comment by joaoceron** [comment]
done
