### ISSUE TITLE
Wrong analyzing tcpdump

### ISSUE THREAD

**Issue by Matix8981** [ddos-clearing-house/ddos_dissector#46]
Hi, i have a issue with analyzing own pcap recorded files (i recorded by the most simplest method), samples included in project works, the same problem it's in docker image.
root@node:~/ddos_dissector# ./ddos_dissector.py -f test.pcap  --summary
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

 _____  _____        _____ _____  ____
|  __ \|  __ \      / ____|  __ \|  _ \
| |  | | |  | | ___| (___ | |  | | |_) |
| |  | | |  | |/ _ \ ___ \| |  | |  _ <
| |__| | |__| | (_) |___) | |__| | |_) |
|_____/|_____/ \___/_____/|_____/|____/

Configuration file provided [ddosdb.conf] not found
[▂] Loading network file: `test.pcap' Exception in thread process:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./ddos_dissector.py", line 433, in pcap_to_df
    df['ip.proto'] = df['ip.proto'].apply(lambda x: protocol_names[x] if (x > 0) else -1)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 4138, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2467, in pandas._libs.lib.map_infer
  File "./ddos_dissector.py", line 433, in <lambda>
    df['ip.proto'] = df['ip.proto'].apply(lambda x: protocol_names[x] if (x > 0) else -1)
KeyError: 112

**Comment by tvdhout** [comment]
The code indeed broke upon encountering IP protocol numbers unknown by the python socket module. 

Your traffic included packets with IP protocol 112, which is used for [Virtual Router Redundancy Protocol](https://en.wikipedia.org/wiki/Virtual_Router_Redundancy_Protocol) or [Common Address Redundancy Protocol](https://en.wikipedia.org/wiki/Common_Address_Redundancy_Protocol).
 
Perhaps your traffic originated from a virtual machine, or through a virtual router? Either way, commit 7b1527f should fix this error and ignore unknown IP protocols. Could you confirm this fixed the error, and if not please elaborate on the traffic you were capturing?

Thank you

**Comment by Matix8981** [comment]
Hi,
Right now correct analyzing the traffic, yes this PCAP it's from virtual machine.
Thanks!
