### ISSUE TITLE
duckdb.duckdb.BinderException with pcap input

### ISSUE THREAD

**Issue by tvdhout** [ddos-clearing-house/ddos_dissector#72]
With a fresh install of the dissector locally and trying to generate fingerprints from the sample pcaps previously found [here](https://github.com/ddos-clearing-house/ddos_dissector/tree/abf9989d9c07e3680c80137db8a4c920aeeff4a3/pcap_samples), DuckDB raises the following error:

```
Traceback (most recent call last):
  File "/Users/thijs/Documents/DDoS/ddos_dissector/src/main.py", line 101, in <module>
    view = parquet_files_to_view(db, pqt_files, filetype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thijs/Documents/DDoS/ddos_dissector/src/util.py", line 433, in parquet_files_to_view
    db.execute(sql)
duckdb.duckdb.BinderException: Binder Error: Cannot mix values of type VARCHAR and INTEGER_LITERAL in COALESCE operator - an explicit cast is required
```

Running on latest MacOS with these dependencies:
- TShark (Wireshark) 4.2.2
- duckdb==0.10.0

**Comment by poorting** [comment]
New duckdb version is more restrictive in implicit casting. Fixed with new pull request, see details there.

**Comment by tvdhout** [comment]
Thanks! That fixed it
